### ISSUE TITLE
non-word output is incorrectly ignored

### ISSUE THREAD

**Issue by cbm755** [catch22/doctest-for-matlab#12]
Consider a test which outputs chars that are not words (in the regular expression sense):

````
>> '[{... + .  [  ] ...'
[{... + .  [  ] ...
````
Then the test will fail, probably because of the `\w` in `example_re` regexp in `doctest_run.m`.

Easy to trigger in Octave because of the way it renders cell-arrays.

**Comment by cbm755** [comment]
I have a fix, subs `\S` (non-whitespace) for `\w` (word).

I'm starting to feel like we need tests for this project.

**Comment by catch22** [comment]
Thanks a bunch for all your work.

I had fixed some small problems that I had stumbled upon after forking the project some years ago, but I never worked on systematically improving the code. I'd certainly be glad to continue merging your pull requests, though, and we should also let upstream know about your changes.

**Comment by cbm755** [comment]
Yes re: contacting upstream.  Especially for non-octave specific stuff.  I've sent him a message.
