### ISSUE TITLE
Octave w/o ">>": Missing space character

### ISSUE THREAD

**Issue by oheim** [catch22/doctest-for-matlab#21]
The automatically insterted “>>” should be followed by a space if the subsequent string does not begin with a space. Otherwise the example block is not detected.

This happens within texinfo files, e.g.
@example
@group
1 + 2
  @result{} ans = 3
@end group
@end example

**Comment by cbm755** [comment]
I cannot reproduce, possibly fixed by 68d5e654da570c6b8bcb481a83c8241db27a5?

**Comment by oheim** [comment]
Yes.
