### ISSUE TITLE
Feature Request: Add summary at the end of test results

### ISSUE THREAD

**Issue by oheim** [catch22/doctest-for-matlab#23]
The coloured output is not good enough to quickly see whether there are failures or not when there are many files to be checked.

Please add a summary line add the end. Useful information: total number of PASS´ed and FAIL´ed example blocks; total number of files without example blocks (see __run_test_suite__ console output as a reference).

**Comment by cbm755** [comment]
Yes good idea.  TODO: also update https://github.com/cbm755/octsympy/blob/master/inst/octsympy_doctests.m

**Comment by cbm755** [comment]
actually, I think we already do this, but I made a bit more elaborate...

**Comment by oheim** [comment]
Sorry, I didn't check for updates before posting the issues… There has been quite some progress—good progress. I could identify more errors with the latest version of doctest and was happy to fix them.

This is the current output for the interval package (at Octave Forge, development version):

    Doctest Summary:
    
      Searched 278 targets: found 326 tests total, 65 targets without tests.
      Extraction errors: 0
      Tests passed: 326/326
      Tests failed: 0

However, the new summary is better ;-) I personally would go without the color. My terminal's color theme does a bad job here.

One comment on the octsympy_doctest.m: Do you really want to release it as a public function? Why would a user run the doctest?

**Comment by cbm755** [comment]
Thanks I've filed https://github.com/cbm755/octsympy/issues/238 about octsympy_doctest.m.  Please post there if you have a nice solution.

I suppose the colour in the summary is a bit over-engineered with little benefit.

1.  I will leave it in the longer output as it makes scanning travis output easier.

2.  I will drop the green "tested passed" highlight.

3.  Do you think I should leave the extraction error and tests failed highlights?  Or drop those too?

**Comment by catch22** [comment]
Reopening, as the discussion is ongoing. Earlier today I made the following changes:
ca573d904b9ecba6768cd5b3cb6f2dc6370937b0 and 5842f1ff040aeaed36d8002eeaa5aed5b1f28bc9

I am quite happy with the color coding as it is now. What do you think?

**Comment by cbm755** [comment]
Here's my logic for dropping green.  If someone's terminal is broken then she probably does mind seeing a bunch of `[` `ESC~` or whatever chars when tests fail.   But if everything is working, quiet output is preferred.

**Comment by cbm755** [comment]
I like your two changes.  Maybe @oheim can comment too.

**Comment by cbm755** [comment]
We're probably bikeshedding the heck out of this (but its not wasted effort as I can propose these changes for Octave `__run_test_suite` too).

Anyway, I'm a little unsure about dropping the background.  What if someone has a green/red/yellow background?  I originally hardcoded black backgroundfor that reason...

**Comment by cbm755** [comment]
some data: `gcc` does not change the background colour despite using green, purple, cyan and others.  But no yellow.  Maybe our warning colour could be purple or something that looks ok on both black and white background.

And people with bright red/green/purple backgrounds deserve it :)

**Comment by cbm755** [comment]
> And people with bright red/green/purple backgrounds deserve it :)

Lest that be taken out of context: someone who really needs such a thing will have overridden the term colours anyway.

**Comment by catch22** [comment]
I concur that using purple or cyan (and not modifying the background color) is a good way to proceed.

**Comment by cbm755** [comment]
OK, see my bikeshed PR

**Comment by cbm755** [comment]
I'll close this, remaining discussion to #31.
