### ISSUE TITLE
Document development process

### ISSUE THREAD

**Issue by catch22** [catch22/doctest-for-matlab#28]
This is the appropriate wiki page: [Development Process](https://github.com/catch22/doctest-for-matlab/wiki/Development-Process)

- [x] Explain self-testing.
- [x] Explain how to publish a new release (octave-forge and tarballs).

**Comment by cbm755** [comment]
Done (or started anyway) in 7db9094.

**Comment by catch22** [comment]
Thanks! I've moved the howto to the [wiki page](https://github.com/catch22/doctest-for-matlab/wiki/Development-Process).
