### ISSUE TITLE
Octave: wrong totals output by "test_anything()"

### ISSUE THREAD

**Issue by cbm755** [catch22/doctest-for-matlab#3]
Here there are 8 tests in total.  `to_test` has size `21x1` and `results` has size 1x8.  Instead of seeing which have tests and which have no tests, I get some random-looking numbers:
````
symfun: OK (64 tests)
@symfun/argnames: OK (115 tests)
@symfun/diff: OK (121 tests)
@symfun/formula: OK (109 tests)
@symfun/int: OK (102 tests)
@symfun/ldivide: OK (117 tests)
@symfun/minus: OK (110 tests)
@symfun/mldivide: OK (47 tests)
@symfun/mpower: OK (97 tests)
@symfun/mrdivide: OK (114 tests)
@symfun/mtimes: OK (103 tests)
@symfun/numel: OK (110 tests)
@symfun/plus: OK (97 tests)
@symfun/power: OK (109 tests)
@symfun/priv_disp_name: OK (101 tests)
@symfun/rdivide: OK (115 tests)
@symfun/subsref: OK (64 tests)
@symfun/symfun: OK (115 tests)
@symfun/symvar: OK (121 tests)
@symfun/times: OK (109 tests)
warning: implicit conversion from scalar to sq_string
````

I'm not sure how this is supposed to work but the error has something to do with the vectorized fprintf:
````
fprintf(out, '%s: OK (%d tests)\n', to_test.name, length(results));
````
note `length(results)` is a scalar (8).

Again, I'll try to look into this further when I get a chance.

**Comment by cbm755** [comment]
seems to happen on matlab as well...

On this line of doctest.m:
````
    result = [result, these_results]
````
shouldn't that save all the `these_results` in a cell-array of length `length(to_test)`?  How else can they be associated back to `to_test{i}.name` for latter display?

**Comment by catch22** [comment]
Thanks. I do not have Matlab available at the moment, but I'll try to investigate with Octave on the week-end.
