### ISSUE TITLE
`doctest doctest_compare` won't work with move to inst/private

### ISSUE THREAD

**Issue by cbm755** [catch22/doctest-for-matlab#32]
'cuz you know its private.

**Comment by catch22** [comment]
The following seems to work for me: `octave --path inst --path inst/private --eval "doctest('doctest_compare');"

Apart from the fact that the doctest itself is broken ;-)

**Comment by catch22** [comment]
We are now testing `doctest_run` and `doctest_compare` in the makefile (but I didn't fix the bug in the test itself).

**Comment by cbm755** [comment]
Haven't checked carefully, but perhaps because of subtly in Octave of `"` strings versus `'` strings.
