### ISSUE TITLE
Number formatting differences

### ISSUE THREAD

**Issue by catch22** [catch22/doctest-for-matlab#35]
By default, MATLAB formats numbers using 4 digits after the decimal point (and some special-casing for 0), while Octave uses 5 digits. Do we want to enforce a certain output format (either `long` or `bank`) so that doctests can be written in a robust way in both systems? Hmm...

**Comment by cbm755** [comment]
I tend to always work in "format short g" which is pretty consistent between the two.  But yes this could be a problem.  I generally would not want "format long" in my docs (unless specifically enabled).

There are a lot of differences, e.g., with displaying cell arrays.

OTOH, I feel like someone writing software is probably targeting either Matlab or Octave.

For example, I want OctSymPy to work in both.  But I don't care if the *doctests* pass on Matlab.  Same as I don't care if the doctests pass on old versions of Octave (even versions where I expect my unit tests to work).
